TIME: 2023-03-22 18:51:13,097 | LEVEL: ERROR | MESSAGE: Internal Server Error: /news/6 | PATH:C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\utils\log.py | STACK: (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Unclosed tag on line 5: 'block'. Looking for one of: endblock."), <traceback object at 0x00000195C048B280>)
Traceback (most recent call last):
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 5: 'block'. Looking for one of: endblock.
TIME: 2023-03-22 18:51:13,098 | LEVEL: ERROR | MESSAGE: "GET /news/6 HTTP/1.1" 500 164617 | PATH:C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\servers\basehttp.py | STACK: None
TIME: 2023-03-27 17:24:42,795 | LEVEL: ERROR | MESSAGE: Internal Server Error: /news/ | PATH:C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\utils\log.py | STACK: (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 7: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x000001F4C6542140>)
Traceback (most recent call last):
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'trans', expected 'endblock'. Did you forget to register or load this tag?
TIME: 2023-03-27 17:24:42,795 | LEVEL: ERROR | MESSAGE: "GET /news/ HTTP/1.1" 500 225944 | PATH:C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\servers\basehttp.py | STACK: None
TIME: 2023-03-28 13:34:47,618 | LEVEL: ERROR | MESSAGE: Internal Server Error: /admin/news/category/ | PATH:C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\utils\log.py | STACK: (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_category.name_en_us'), <traceback object at 0x000001D28FA16E40>)
Traceback (most recent call last):
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: news_category.name_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\contrib\admin\options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\contrib\admin\options.py", line 2068, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: news_category.name_en_us
TIME: 2023-03-28 13:34:47,620 | LEVEL: ERROR | MESSAGE: "GET /admin/news/category/ HTTP/1.1" 500 160650 | PATH:C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\servers\basehttp.py | STACK: None
TIME: 2023-03-29 13:01:47,413 | LEVEL: ERROR | MESSAGE: Internal Server Error: /news/ | PATH:C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\utils\log.py | STACK: (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError('Could not parse the remainder: \'<\' from \'"Time zone:"<\''), <traceback object at 0x00000276E41FF200>)
Traceback (most recent call last):
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\templatetags\i18n.py", line 403, in do_translate
    message_string = parser.compile_filter(bits[1])
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '<' from '"Time zone:"<'
TIME: 2023-03-29 13:01:47,417 | LEVEL: ERROR | MESSAGE: "GET /news/ HTTP/1.1" 500 268146 | PATH:C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\servers\basehttp.py | STACK: None
TIME: 2023-03-29 13:55:38,662 | LEVEL: ERROR | MESSAGE: Internal Server Error: /news/ | PATH:C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\utils\log.py | STACK: (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 58: 'set_timezone'. Did you forget to register or load this tag?"), <traceback object at 0x00000169FB34EC40>)
Traceback (most recent call last):
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'set_timezone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 58: 'set_timezone'. Did you forget to register or load this tag?
TIME: 2023-03-29 13:55:38,662 | LEVEL: ERROR | MESSAGE: "GET /news/ HTTP/1.1" 500 258061 | PATH:C:\Users\Friend\PycharmProjects\Django_Project_NewsPaper1\venv\lib\site-packages\django\core\servers\basehttp.py | STACK: None
